# Dockerfile.frontend
# Build stage
FROM node:18 AS build-stage
WORKDIR /app
RUN apt-get update && apt-get install -y git
# clone your frontend repo (change repo to your actual repo if needed)
RUN git clone https://github.com/likitha2505/project_frontend.git .
RUN npm ci
RUN npm run build

# Serve with nginx
FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 81
CMD ["nginx", "-g", "daemon off;"]
